sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install curl

install:
  - docker pull harshjv/texlive-2015
  - curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox.sh
  - chmod +x dropbox.sh

before_script:
  - mkdir _build

script:
  - docker run --rm -it -v $(pwd):/var/texlive harshjv/texlive-2015 lualatex --output-directory /var/texlive/_build curriculum-vitae.tex

after_success:
  - ./dropbox.sh upload _build/curriculum-vitae.pdf curriculum-vitae-latest.pdf
  - ./dropbox.sh upload _build/curriculum-vitae.pdf curriculum-vitae-b${TRAVIS_BUILD_NUMBER}.pdf
